nexus/nexus/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    return render(request, "home.html")

@login_required
def work_in_progress(request):
    return render(request, "work_in_progress_full_page.html")

handler404 = 'core.views.handler404'

urlpatterns = [
    path('', index, name='index'),
    path('work_in_progress/', work_in_progress, name='work_in_progress'),
    path('admin/', admin.site.urls),
    # path('explorer/', include('explorer.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('core/', include('core.urls')),
    path('users/', include('users.urls')),
    path('patches/', include('patches.urls')),
    path('shifts/', include('shifts.urls')),
    path('SIs/', include('SIs.urls')),
    path('students/', include('students.urls')),
    path('payrolls/', include('payrolls.urls')),
    path('tutors/', include('tutors.urls')),
    path('htmx_apis/', include('htmx_apis.urls')),
    path('ours/', include('ours.urls')),
    path('oa/', include('oa.urls')),
    path('hijack/', include('hijack.urls')),
]

nexus/oa/urls.py
from django.urls import path, re_path

from .views.shift_request import (
    shift_requests,
    change_request,
    drop_request,
    add_request,
    add_request_form,
    change_request_form,
    drop_request_form,
)

SHIFT_REQUEST = [
    path('shift_requests/', shift_requests, name='oa_shift_requests'),
    path('add_request/<str:request_state>/', add_request, name='oa_add_request'),
    path('change_request/<str:request_state>/', change_request, name='oa_change_request'),
    path('drop_request/<str:request_state>/', drop_request, name='oa_drop_request'),
    path('add_request_form/<int:req_id>/', add_request_form, name='oa_add_request_form'),
    path('change_request_form/<int:req_id>/', change_request_form, name='oa_change_request_form'),
    path('drop_request_form/<int:req_id>/', drop_request_form, name='oa_drop_request_form'),
]

urlpatterns = (
    SHIFT_REQUEST
)

nexus/shifts/urls.py
from django.urls import path, re_path

from .views.users_shift import (
    users_shift,
    user_calendar,
    get_user_shifts,
    add_shift,
    edit_or_drop_shift,
    drop_shift,
    edit_shift,
    add_edit_recurring,
    add_recurring,
    edit_recurring,
    record_meeting,
    UserAutocomplete,    
)

from .views.bulk_shift import (
    group_shift,
    group_add_shift,
    GroupAutocomplete,
)

from .views.schedule import (
    schedule_for_all_course,
)

USERS_SHIFT_URLS = [
    path('users_shift/', users_shift, name='users_shift'),
    path('user_calender/<int:user_id>/', user_calendar, name='user_calendar'),
    path('user_calender/get_user_shifts/', get_user_shifts, name='get_user_shifts'),
    path('add_shift/<int:user_id>/', add_shift, name='add_shift'),
    path('edit_or_drop_shift/<int:shift_id>/', edit_or_drop_shift, name='edit_or_drop_shift'),
    path('drop_shift/<int:shift_id>/', drop_shift, name='drop_shift'),
    path('edit_shift/<int:shift_id>/', edit_shift, name='edit_shift'),
    path('add_edit_recurring/<int:user_id>/', add_edit_recurring, name='add_edit_recurring'),
    path('add_recurring/<int:user_id>/', add_recurring, name='add_recurring'),
    path('edit_recurring/<int:rshift_id>/', edit_recurring, name='edit_recurring'),
    path('record_meeting/<int:user_id>/', record_meeting, name='record_meeting'),
    re_path(r'^users_shift/autocomplete/$', UserAutocomplete.as_view(), name='user-autocomplete'),
]

BULK_SHIFT_URLS = [
    path('group_shift/', group_shift, name='group_shift'),
    path('group_add_shift/<int:group_id>/', group_add_shift, name='group_add_shift'),
    re_path(r'^group_shift/autocomplete/$', GroupAutocomplete.as_view(), name='group-autocomplete'),
]

SCHEDULE_URLS = [
    path('schedule_for_all_course/', schedule_for_all_course, name='schedule_for_all_course')
]

urlpatterns = (
    USERS_SHIFT_URLS +
    BULK_SHIFT_URLS +
    SCHEDULE_URLS
)

nexus/shifts/models.py
from datetime import datetime, timedelta
from django.utils import timezone

from django.db import models

from core.models import (
    Buildings,
    Day,
    Holiday,
    Semester,
    DaySwitch,
    ClassTimes,
)

from users.models import (
    Positions,
    NexusUser,
    PositionChoices,
)

from payrolls.models import (
    Payroll,
    PayrollStatus,
    PayrollNotSigned,
    PayrollNotInHR,
)

def get_weekend(date):
    while date.weekday() != 5:
        date += timedelta(days=1)
    return date

class ShiftKind(models.TextChoices):
    SI_SESSION = "SI Session"
    TUTOR_DROP_IN = "Tutor Drop-In"
    TUTOR_APPOINTMENT = "Tutor Appointment"
    GROUP_TUTORING = "Group Tutoring"
    TRAINING = "Training"
    OBSERVATION = "Observation"
    CLASS = "Class"
    PREPARATION = "Preparation"
    MEETING = "Meeting"
    OURS_MENTOR_HOURS = "OURS Mentor Hours"
    OA_HOURS = "OA Hours"
    OTHER = "Other"

def recurring_shift_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    filename = filename.replace(' ', '_')
    filename = datetime.now().strftime("%Y-%m-%d_%H:%M:%S") + '_' + filename
    return f'rec_shift_{instance.position.id}/{filename}'

class RecurringShift(models.Model):
    position = models.ForeignKey(
        to=Positions,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        help_text="The position that this recurring shift is for."
    )
    
    day = models.PositiveSmallIntegerField(
        choices=Day.choices,
        null=False,
        blank=False,
        help_text="The day of the week that this recurring shift is for."
    )
    
    start_time = models.TimeField(
        null=False,
        blank=False,
        help_text="The start time of the recurring shift."
    )
    
    duration = models.DurationField(
        null=False,
        blank=False,
        help_text="The duration of the recurring shift."
    )
    
    building = models.ForeignKey(
        to=Buildings,
        on_delete=models.RESTRICT,
        null=False,
        blank=False,
        help_text="The building the recurring shift is in."
    )
    
    room = models.CharField(
        max_length=10,
        null=False,
        blank=False,
        help_text="The room the recurring shift is in."
    )
    
    kind = models.CharField(
        max_length=30,
        choices=ShiftKind.choices,
        null=False,
        blank=False,
        help_text="The kind of recurring shift."
    )
    
    note = models.TextField(
        null=True,
        blank=True,
        help_text="Any notes for the recurring shift. This will be copied to all shifts."
    )
    
    document = models.FileField(
        null=True,
        blank=True,
        upload_to=recurring_shift_directory_path,
        help_text="Any attached document for the recurring shift. This will be copied to all shifts."
    )
    
    require_punch_in_out = models.BooleanField(
        default=False,
        help_text="Whether or not the recurring shift requires punch in/out."
    )
    
    start_date = models.DateField(
        null=False,
        blank=False,
        help_text="The start date of the recurring shift."
    )
    
    end_date = models.DateField(
        null=False,
        blank=False,
        help_text="The end date of the recurring shift. This is inclusive."
    )
    
    class_time = models.ForeignKey(
        to=ClassTimes,
        on_delete=models.RESTRICT,
        null=True,
        blank=True,
        help_text="The class time that this recurring shift is for."
    )
    
    def save(self, *args, **kwargs):
        update = self.id is not None
        recurring_shift = super(RecurringShift, self).save(*args, **kwargs)
        
        todays_date = timezone.localdate(timezone.now())
        start_date = self.start_date if self.start_date > todays_date else todays_date
        
        if update:
            shifts = Shift.objects.filter(recurring_shift=self, start__date__gte=start_date).all()
            
            for shift in shifts:
                shift.delete()
        
        while (start_date.weekday()+1)%7 != self.day:
            start_date += timedelta(days=1)
        
        if start_date > self.end_date:
            return recurring_shift
        
        active_sem = Semester.objects.get_active_semester()
        holidays = Holiday.objects.filter(semester=active_sem, date__gte=start_date, date__lte=self.end_date).values_list('date', flat=True)
        day_switches = DaySwitch.objects.filter(semester=active_sem, date__gte=start_date, date__lte=self.end_date).all()
        day_switches_dates = day_switches.values_list('date', flat=True)
        date_which_follow_day = day_switches.filter(day_to_follow=self.day).values_list('date', flat=True)
        
        for date in date_which_follow_day:
            Shift.objects.create(
                position=self.position,
                start=timezone.make_aware(datetime.combine(date, self.start_time)),
                duration=self.duration,
                building=self.building,
                room=self.room,
                kind=self.kind,
                note=self.note,
                document=self.document,
                require_punch_in_out=self.require_punch_in_out,
                recurring_shift=self,
            )
        
        while start_date <= self.end_date:
            if not (start_date in holidays or start_date in day_switches_dates):
                Shift.objects.create(
                    position=self.position,
                    start=timezone.make_aware(datetime.combine(start_date, self.start_time)),
                    duration=self.duration,
                    building=self.building,
                    room=self.room,
                    kind=self.kind,
                    note=self.note,
                    document=self.document,
                    require_punch_in_out=self.require_punch_in_out,
                    recurring_shift=self,
                )
            start_date += timedelta(days=7)
        
        return recurring_shift
    
    def delete(self):
        todays_date = timezone.localdate(timezone.now())
        for shift in Shift.objects.filter(recurring_shift=self, start__date__gte=todays_date).all():
            shift.delete()
        super(RecurringShift, self).delete()

def shift_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    filename = filename.replace(' ', '_')
    filename = datetime.now().strftime("%Y-%m-%d_%H:%M:%S") + '_' + filename
    return f'shift_{instance.position.id}/{filename}'

class ShiftManager(models.Manager):
    def filter(self, *args, **kwargs):
        # Only add dropped=False if not already specified
        if 'dropped' not in kwargs:
            kwargs['dropped'] = False
        return super().filter(*args, **kwargs)

class Shift(models.Model):
    position = models.ForeignKey(
        to=Positions,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        help_text="The position that this shift is for."
    )
    
    start = models.DateTimeField(
        null=False,
        blank=False,
        help_text="The start date/time of the shift."
    )
    
    duration = models.DurationField(
        null=False,
        blank=False,
        help_text="The duration of the shift."
    )
    
    original_start = models.DateTimeField(
        default=None,
        null=True,
        blank=False,
        help_text="The start orignial date/time of the shift."
    )
    
    original_duration = models.DurationField(
        default=None,
        null=True,
        blank=False,
        help_text="The original duration of the shift."
    )

    building = models.ForeignKey(
        to=Buildings,
        on_delete=models.RESTRICT,
        null=False,
        blank=False,
        help_text="The building the shift is in."
    )
    
    room = models.CharField(
        max_length=10,
        null=False,
        blank=False,
        help_text="The room the shift is in."
    )
    
    kind = models.CharField(
        max_length=30,
        choices=ShiftKind.choices,
        null=False,
        blank=False,
        help_text="The kind of shift."
    )
    
    note = models.TextField(
        null=True,
        blank=True,
        help_text="Any notes for the shift."
    )
    
    document = models.FileField(
        null=True,
        blank=True,
        upload_to=shift_directory_path,
        help_text="Any attached document for the shift."
    )
    
    require_punch_in_out = models.BooleanField(
        default=False,
        help_text="Whether or not the shift requires punch in/out."
    )
    
    recurring_shift = models.ForeignKey(
        to=RecurringShift,
        on_delete=models.SET_NULL,
        default=None,
        null=True,
        blank=True,
    )
    
    dropped = models.BooleanField(
        default=False,
        help_text="Whether or not the shift is dropped."
    )
    
    objects = ShiftManager()
    
    def save(self, *args, **kwargs):
        update = self.id is not None
        if self.dropped:
            return super(Shift, self).save(*args, **kwargs)
        if update:
            old_shift = Shift.objects.get(id=self.id)
            payroll = Payroll.objects.get(position=old_shift.position, week_end=get_weekend(timezone.localdate(old_shift.start)))
            start_weekday = timezone.localdate(old_shift.start).weekday()
            change_payroll =  payroll.not_signed
            att_info = AttendanceInfo.objects.get(shift=old_shift)
            if att_info.signed:
                att_info.signed = False
                att_info.attended = False
                att_info.save()
                self.recurring_shift = None
                self.require_punch_in_out = False
                change_payroll = payroll.not_in_hr
                change_payroll.approved_by_user = False

nexus/shifts/views/bulk_shift.py
from datetime import timedelta

from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.db.models import Q

from dal import autocomplete

from core.views import restrict_to_http_methods, restrict_to_groups

from users.models import (
    NexusUser,
    PositionGroups,
)

from ..models import (
    Shift,
    RecurringShift,
)

from ..forms.bulk_shift import (
    SelectGroup,
    BulkShiftAddForm,
)

@login_required
@restrict_to_http_methods("GET", "POST")
@restrict_to_groups("Staff Admin", "SI Supervisor", "Tutor Supervisor", "OURS Supervisor", "Payroll Supervisor")
def group_shift(request):
    if request.method == "POST":
        form = SelectGroup(request.POST)
        if not form.is_valid():
            messages.error(request, f"Form Error: {form.errors}")
            return render(request, 'bulk_shift_response.html')
        group = form.cleaned_data['group']
        members = group.members.all()
        context = {
            'members': members,
            'group_id': group.id,
            'success': True,
        }
        return render(request, 'bulk_shift_response.html', context)
    form = SelectGroup()
    return render(request, 'bulk_shift.html', {'form': form})


@login_required
@restrict_to_http_methods("GET", "POST")
@restrict_to_groups("Staff Admin", "SI Supervisor", "Tutor Supervisor", "OURS Supervisor", "Payroll Supervisor")
def group_add_shift(request, group_id):
    if request.method == "POST":
        form = BulkShiftAddForm(group_id, request.POST, request.FILES)
        if not form.is_valid():
            messages.error(request, f"Form Error: {form.errors}")
            return render(request, 'group_add_shift_response.html')
        data = form.cleaned_data
        group = PositionGroups.objects.get(id=group_id)
        members = group.members.all()
        for member in members:
            Shift.objects.create(
                position=member,
                start=data['start'],
                duration=timedelta(hours=data['hours'], minutes=data['minutes']),
                building=data['building'],
                room=data['room'],
                kind=data['kind'],
                note=data['note'],
                document=data['document'],
                require_punch_in_out=data['require_punch_in_out'],
            )
        messages.success(request, f"Successfully added shifts to {group.name}")
        context = {
            'success': True,
            'group_id': group_id,
        }
        return render(request, 'group_add_shift_response.html', context)
    form = BulkShiftAddForm(group_id)
    return render(request, 'just_form.html', {'form': form})

class GroupAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = PositionGroups.objects.all()
        if self.q:
            qs = qs.filter(name__icontains=self.q).all()
        return qs

nexus/shifts/templates/add_edit_recurring.html
{% load crispy_forms_tags %}

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th class="text-center" scope="col">Kind</th>
      <th class="text-center" scope="col">Day</th>
      <th class="text-center" scope="col">Time</th>
      <th class="text-center" scope="col">Location</th>
      <th class="text-center" scope="col">Edit</th>
    </tr>
  </thead>
  <tbody id="current_recurring-body">
    <tr>
      <th class="text-center" colspan="5">Current Recurring Shifts</th>
    </tr>
    {% if current_recurring_shifts %}
      {% for rshift in current_recurring_shifts %}
      <tr id="rt-{{rshift.id}}">
        <td class="text-center">{{ rshift.kind }}</td>
        <td class="text-center">{{ rshift.get_day_display }}</td>
        <td class="text-center">{{ rshift.start_time }}</td>
        <td class="text-center">
          {{ rshift.building.short_name }}-{{ rshift.room }}
        </td>
        <td class="text-center">
          <a
            href=""
            hx-get="{% url 'edit_recurring' rshift.id %}"
            hx-trigger="click"
            hx-target="#edit-recurring-form"
            ><i class="bi bi-pencil-square"></i
          ></a>
        </td>
      </tr>
      {% endfor %}
    {% else %}
    <tr>
      <td class="text-center" colspan="5">There are no active recurring shifts</td>
    </tr>
    {% endif %}
    
  </tbody>
  <tbody id="inactive_recurring-body">
    <tr>
      <th class="text-center" colspan="5">Inactive Recurring Shifts</th>
    </tr>
    {% if inactive_recurring_shifts %}
      {% for rshift in inactive_recurring_shifts %}
      <tr id="rt-{{rshift.id}}">
        <td class="text-center">{{ rshift.kind }}</td>
        <td class="text-center">{{ rshift.get_day_display }}</td>
        <td class="text-center">{{ rshift.start_time }}</td>
        <td class="text-center">
          {{ rshift.building.short_name }}-{{ rshift.room }}
        </td>
        <td class="text-center">
          <a
            href=""
            hx-get="{% url 'edit_recurring' rshift.id %}"
            hx-trigger="click"
            hx-target="#edit-recurring-form"
            ><i class="bi bi-pencil-square"></i
          ></a>
        </td>
      </tr>
      {% endfor %}
    {% else %}
    <tr>
      <td class="text-center" colspan="5">There are no inactive recurring shifts</td>
    </tr>
    {% endif %}
    
  </tbody>
</table>

<div id="edit-recurring-message"></div>
<div id="edit-recurring-form">{% crispy edit_form %}</div>

<div id="add-recurring-message"></div>
<div id="add-recurring-form">
  <div
    hx-get="{% url 'add_recurring' user_id %}"
    hx-trigger="load"
    hx-target="this"
    hx-swap="outerHTML"
  ></div>
</div>

nexus/shifts/templates/add_recurring_response.html
{% if success %}
<tbody id="recurring-body">
  <tr id="rt-{{rshift.id}}" class="new-add">
    <td class="text-center">{{ rshift.kind }}</td>
    <td class="text-center">{{ rshift.get_day_display }}</td>
    <td class="text-center">{{ rshift.start_time }}</td>
    <td class="text-center">
      {{ rshift.building.short_name }}-{{ rshift.room }}
    </td>
    <td class="text-center">
      <a
        href=""
        hx-get="{% url 'edit_recurring' rshift.id %}"
        hx-trigger="click"
        hx-target="#edit-recurring-form"
        ><i class="bi bi-pencil-square"></i
      ></a>
    </td>
  </tr>
</tbody>
{% endif %}

<div id="add-recurring-message">{% include 'alerts.html' %}</div>

{% if success %}
<div id="add-recurring-form">
  <div
    hx-get="{% url 'add_recurring' user_id %}"
    hx-target="this"
    hx-trigger="load"
    hx-swap="outerHTML"
  ></div>
</div>
{% endif %}

nexus/shifts/templates/add_shift_response.html
<div id="add-shift-message">{% include 'alerts.html' %}</div>

{% if success %}
<div id="add-shift-form">
  <div
    hx-get="{% url 'add_shift' user_id %}"
    hx-target="this"
    hx-swap="outerHTML"
    hx-trigger="load"
  ></div>
</div>
{% endif %}

nexus/shifts/templates/bulk_shift.html
<!--Extends base template-->
{% extends "base.html" %}
<!--So forms look good-->
{% load crispy_forms_tags %}

<!--Content of the page-->
{% block content %}
<h1 class="text-center">Manage Bulk Shift</h1>
<div id="look-up-form-message"></div>
{% crispy form %}
<p class="text-center"><b>Look up a group to see it members.</b></p>
<hr />
<table class="table">
  <thead>
    <tr>
      <th class="text-center" scope="col">Last Name</th>
      <th class="text-center" scope="col">First Name</th>
      <th class="text-center" scope="col">Position</th>
    </tr>
  </thead>
  <tbody id="members-body"></tbody>
</table>

{% endblock %} {% block bottom %}
<div class="accordion-item">
  <h2 class="accordion-header" id="flush-headingOne">
    <button
      class="accordion-button collapsed d-block text-center"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#flush-collapseOne"
      aria-expanded="false"
      aria-controls="flush-collapseOne"
      id="flush-collapseOne-button"
    >
      <h3>Add Group Shift</h3>
    </button>
  </h2>
  <div
    id="flush-collapseOne"
    class="accordion-collapse collapse"
    aria-labelledby="flush-headingOne"
    data-bs-parent="#accordionFlushExample"
  >
    <div class="accordion-body">
      <p class="text-center">
        Please look up a group for whom you want to add shift.
      </p>
      <div id="add-shift-message"></div>
      <div id="add-shift-form"></div>
    </div>
  </div>
</div>
{% endblock %}

nexus/shifts/templates/bulk_shift_response.html
{% if success %}
<tbody id="members-body">
  {% for position in members %}
  <tr id="mt-{{position.id}}">
    <td class="text-center">{{ position.user.last_name }}</td>
    <td class="text-center">{{ position.user.first_name }}</td>
    <td class="text-center">{{ position.get_position_display }}</td>
  </tr>
  {% endfor %}
</tbody>
{% endif %}

<div id="look-up-form-message">{% include 'alerts.html' %}</div>

{% if success %}
<div id="add-shift-message"></div>
<div id="add-shift-form">
  <div
    hx-get="{% url 'group_add_shift' group_id %}"
    hx-target="this"
    hx-swap="outerHTML"
    hx-trigger="intersect"
  ></div>
</div>
{% endif %}

nexus/shifts/templates/delete_shift.html
<div id="edit-shift-message">{% include 'alerts.html' %}</div>
<div id="edit-shift-form">
  {% if not success %} {% include 'edit_or_drop.html' %} {% endif %}
</div>

nexus/shifts/templates/edit_or_drop.html
<div class="row">
  <button
    hx-delete="{% url 'drop_shift' shift_id %}"
    hx-trigger="click"
    hx-swap="multi:#edit-shift-message:innerHTML,#edit-shift-form:innerHTML"
    class="btn btn-danger d-block mx-auto col-4"
  >
    Drop Shift
  </button>
  <button
    hx-get="{% url 'edit_shift'  shift_id %}"
    hx-trigger="click"
    hx-swap="multi:#edit-shift-message:innerHTML,#edit-shift-form:innerHTML"
    class="btn btn-primary d-block mx-auto col-4"
  >
    Edit Shift
  </button>
</div>

nexus/shifts/templates/edit_recurring_response.html
{% if success %}
<tr id="rt-{{rshift.id}}">
  <td class="text-center">{{ rshift.kind }}</td>
  <td class="text-center">{{ rshift.get_day_display }}</td>
  <td class="text-center">{{ rshift.start_time }}</td>
  <td class="text-center">
    {{ rshift.building.short_name }}-{{ rshift.room }}
  </td>
  <td class="text-center">
    <a
      href=""
      hx-get="{% url 'edit_recurring' rshift.id %}"
      hx-trigger="click"
      hx-target="#edit-recurring-form"
      ><i class="bi bi-pencil-square"></i
    ></a>
  </td>
</tr>
{% endif %}

<div id="edit-recurring-message">{% include 'alerts.html' %}</div>

nexus/shifts/templates/edit_shift_initial.html
{% load crispy_forms_tags %}

<div id="edit-shift-message">{% include 'alerts.html' %}</div>

<div id="edit-shift-form">{% crispy form %}</div>

nexus/shifts/templates/edit_shift_response.html
<div id="edit-shift-message">{% include 'alerts.html' %}</div>

{% if success %}
<div id="edit-shift-form">
  <div
    hx-get="{% url 'edit_shift' shift_id %}"
    hx-target="this"
    hx-swap="outerHTML"
    hx-trigger="load"
  ></div>
</div>
{% endif %}

nexus/shifts/templates/group_add_shift_response.html
<div id="add-shift-message">{% include 'alerts.html' %}</div>

{% if success %}
<div id="add-shift-form">
  <div
    hx-get="{% url 'group_add_shift' group_id %}"
    hx-target="this"
    hx-swap="outerHTML"
    hx-trigger="load"
  ></div>
</div>
{% endif %}

nexus/shifts/templates/look_up_response.html
<div id="look-up-message">{% include 'alerts.html' %}</div>

{% if success %}
<div id="calendar">
  <div
    hx-get="{% url 'user_calendar' curr_user.id %}"
    hx-swap="multi:#colors:innerHTML,#calendar:innerHTML"
    hx-trigger="intersect"
  ></div>
</div>

<div id="add-shift">
  <div id="add-shift-message"></div>
  <div id="add-shift-form">
    <div
      hx-get="{% url 'add_shift' curr_user.id %}"
      hx-target="this"
      hx-swap="outerHTML"
      hx-trigger="intersect"
    ></div>
  </div>
</div>

<div id="add-edit-recurring">
  <div id="add-edit-recurring-message"></div>
  <div id="add-edit-recurring-form">
    <div
      hx-get="{% url 'add_edit_recurring' curr_user.id %}"
      hx-target="this"
      hx-swap="outerHTML"
      hx-trigger="intersect"
    ></div>
  </div>
</div>

<div id="record-meeting">
  <div id="record-meeting-message"></div>
  <div id="record-meeting-form">
    <div
      hx-get="{% url 'record_meeting' curr_user.id %}"
      hx-target="this"
      hx-swap="outerHTML"
      hx-trigger="intersect"
    ></div>
  </div>
</div>
{% endif %}

nexus/shifts/templates/schedule_all_courses.html
<!--Extends base template-->
{% extends "base.html" %}
<!--So forms look good-->
{% load crispy_forms_tags %} {% load schedule %}

<!--Content of the page-->
{% block content %}
<h1 class="text-center">Schedule For Courses</h1>
{% comment %}
<div id="look-up-form-message"></div>
{% crispy form %} {% endcomment %}
<hr />
{% comment %}
<p class="text-center"><b>Look up a user to see thier shifts.</b></p>
<div>
  <div id="colors"></div>
  <hr />
  <div id="calendar"></div>
</div>
{% endcomment %} {% include 'color_coder.html' %}
<div class="table-responsive">
  <table class="table table-bordered text-center equal-col">
    <thead class="stickyHeader">
      <tr>
        <th scope="col" class="text-uppercase align-middle">Course</th>
        {% for day in dates %}
        <th scope="col" class="text-uppercase align-middle">
          <span>{{ day|date:"l" }}</span>
          <div>{{ day|date:"m/d" }}</div>
        </th>
        {% endfor %}
      </tr>
    </thead>
    <tbody>
      {% for course, days in schedule.items %}
      <tr>
        <td class="align-middle">{{course}}</td>
        {% for day in days %} {% if day|length == 0 %}
        <td class="bg-light-gray"></td>
        {% else %}
        <td>
          {% for s in day %}
          <div class="margin-10px-top">
            {% if s.kind == "SI Session" %}
            <div
              class="font-size16 text-break text-wrap"
              style="margin-bottom: 10px"
            >
              faculty
            </div>
            {% endif %}
            <div
              class="padding-5px-tb padding-15px-lr border-radius-5 margin-10px-bottom text-white font-size16 xs-font-size13"
              style="background-color: {{s.kind|color_coder}}"
            >
              {{s.building.short_name}}-{{s.room}}
            </div>
            <div class="margin-10px-top font-size14">
              {{s.start| date:"h:i A" |lower}} -
              {{s.start|add_datetime:s.duration|date:"h:i A"|lower}}
            </div>
            <div class="font-size13 text-break text-wrap">
              {{s.position.user}}
            </div>
          </div>
          {% if not forloop.last %}
          <div
            class="mb-1 mt-1"
            style="
              height: 2px;
              background-color: rgba(0, 0, 0, 0.2);
              border-radius: 1px;
            "
          ></div>
          {% endif %} {% endfor %}
        </td>
        {% endif %} {% endfor %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}